version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moneydb
      MYSQL_USER: moneyuser
      MYSQL_PASSWORD: moneypass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: moneyuser
      DB_PASSWORD: moneypass
      DB_NAME: moneydb
    depends_on:
      - db

volumes:
  db_data: 